=== Zaaim-Halim/PageRank_algo/pageRank.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <xsd:element name="graphe">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element name="nodes">
               <xsd:complexType>
                  <xsd:sequence>
                     <xsd:element name="node" type="nodetype" minOccurs="1" maxOccurs="unbounded" />
                  </xsd:sequence>
               </xsd:complexType>
            </xsd:element>
            <xsd:element name="edges">
               <xsd:complexType>
                  <xsd:sequence>
                     <xsd:element name="edge" type="edgetype" minOccurs="1" maxOccurs="unbounded" />
                  </xsd:sequence>
               </xsd:complexType>
            </xsd:element>
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>
   <xsd:complexType name="nodetype">
      <xsd:attribute name="id" type="xsd:string" use="required" />
   </xsd:complexType>
   <xsd:complexType name="edgetype">
      <xsd:attribute name="source" type="xsd:string" use="required" />
      <xsd:attribute name="target" type="xsd:string" use="required" />
   </xsd:complexType>
</xsd:schema>

=== Zaaim-Halim/PageRank_algo/pageRank.xml
<?xml version="1.0" encoding="UTF-8"?>
<graphe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pageRank.xsd">
   <nodes>
      <node id="I" />
      <node id="E" />
      <node id="B" />
      <node id="H" />
      <node id="L" />
      <node id="M" />
      <node id="G" />
      <node id="F" />
      <node id="D" />
      <node id="A" />
      <node id="C" />
   </nodes>
   <edges>
      <edge source="I" target="E" />
      <edge source="I" target="B" />
      <edge source="E" target="B" />
      <edge source="E" target="F" />
      <edge source="E" target="D" />
      <edge source="B" target="C" />
      <edge source="H" target="E" />
      <edge source="H" target="B" />
      <edge source="L" target="E" />
      <edge source="M" target="E" />
      <edge source="G" target="E" />
      <edge source="G" target="B" />
      <edge source="F" target="E" />
      <edge source="F" target="B" />
      <edge source="D" target="A" />
      <edge source="D" target="B" />
      <edge source="C" target="B" />
   </edges>
</graphe>
